name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Deploy NodeJS app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22

        script: |
          cd /home/node-demo-app/
          git pull origin main
          npm install --production
          pm2 restart NodeDemo
