name: Node.js CI

on:
  push:
    branches:
    - main

jobs:
  my_job:
    runs-on: ubuntu-18.04
    steps:
    - name: Deploy
      run: |
          cd ~/home/node-demo-app
          git pull origin main
